import type {
  Account,
  Category,
  DashboardSummary,
  Label,
  Profile,
  RecurringTransaction,
  Transaction,
} from '../types/domain'

export const demoUserId = 'demo-user'
const now = '2026-09-07T12:00:00.000Z'

export const demoProfile: Profile = {
  id: demoUserId,
  email: 'marko@example.com',
  displayName: 'Marko Božić',
  primaryCurrency: 'EUR',
  theme: 'dark',
  createdAt: now,
  updatedAt: now,
}

export const demoAccounts: Account[] = [
  {
    id: 'account-current',
    userId: demoUserId,
    name: 'Tekući račun',
    type: 'current',
    currency: 'EUR',
    initialBalance: 4200,
    balance: 6840,
    color: '#6bd8cb',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'account-visa',
    userId: demoUserId,
    name: 'Visa Gold',
    type: 'credit_card',
    currency: 'EUR',
    initialBalance: 1400.5,
    balance: 1320.5,
    color: '#c0c1ff',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'account-savings',
    userId: demoUserId,
    name: 'Fond štednje',
    type: 'savings',
    currency: 'EUR',
    initialBalance: 4000,
    balance: 4000,
    color: '#4edea3',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'account-wallet',
    userId: demoUserId,
    name: 'Novčanik',
    type: 'wallet',
    currency: 'EUR',
    initialBalance: 260,
    balance: 260,
    color: '#f59e0b',
    createdAt: now,
    updatedAt: now,
  },
]

export const demoCategories: Category[] = [
  {
    id: 'category-food',
    userId: demoUserId,
    name: 'Hrana i namirnice',
    icon: 'shopping-cart',
    color: '#6bd8cb',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'category-groceries',
    userId: demoUserId,
    parentId: 'category-food',
    name: 'Namirnice',
    icon: 'shopping-basket',
    color: '#6bd8cb',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'category-housing',
    userId: demoUserId,
    name: 'Stanovanje i režije',
    icon: 'house',
    color: '#c0c1ff',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'category-subscriptions',
    userId: demoUserId,
    name: 'Pretplate i servisi',
    icon: 'calendar-days',
    color: '#4edea3',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'category-transport',
    userId: demoUserId,
    name: 'Prijevoz i gorivo',
    icon: 'fuel',
    color: '#7bd5e8',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'category-salary',
    userId: demoUserId,
    name: 'Plaća',
    icon: 'briefcase-business',
    color: '#4edea3',
    type: 'income',
    createdAt: now,
    updatedAt: now,
  },
]

export const demoLabels: Label[] = [
  {
    id: 'label-family',
    userId: demoUserId,
    name: 'family',
    color: '#6bd8cb',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'label-business',
    userId: demoUserId,
    name: 'business',
    color: '#c0c1ff',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'label-recurring',
    userId: demoUserId,
    name: 'subscription',
    color: '#f59e0b',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'label-reimbursable',
    userId: demoUserId,
    name: 'reimbursable',
    color: '#4edea3',
    createdAt: now,
    updatedAt: now,
  },
]

export const demoTransactions: Transaction[] = [
  {
    id: 'tx-konzum',
    userId: demoUserId,
    accountId: 'account-visa',
    categoryId: 'category-groceries',
    type: 'expense',
    amount: 42.5,
    currency: 'EUR',
    exchangeRate: 1,
    amountBase: 42.5,
    description: 'Konzum d.d.',
    merchant: 'Konzum',
    transactionDate: '2026-09-07',
    notes: '',
    labelIds: ['label-family'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tx-salary',
    userId: demoUserId,
    accountId: 'account-current',
    categoryId: 'category-salary',
    type: 'income',
    amount: 2800,
    currency: 'EUR',
    exchangeRate: 1,
    amountBase: 2800,
    description: 'Mjesečna plaća',
    merchant: 'Acme d.o.o.',
    transactionDate: '2026-09-06',
    labelIds: ['label-business'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tx-transfer-out',
    userId: demoUserId,
    accountId: 'account-current',
    type: 'transfer',
    amount: 500,
    currency: 'EUR',
    exchangeRate: 1,
    amountBase: 500,
    description: 'Interni prijenos',
    transactionDate: '2026-09-05',
    transferGroupId: 'transfer-sep-05',
    labelIds: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tx-netflix',
    userId: demoUserId,
    accountId: 'account-visa',
    categoryId: 'category-subscriptions',
    type: 'expense',
    amount: 13.99,
    currency: 'EUR',
    exchangeRate: 1,
    amountBase: 13.99,
    description: 'Netflix Standard',
    merchant: 'Netflix',
    transactionDate: '2026-09-04',
    recurringTransactionId: 'rec-netflix',
    labelIds: ['label-recurring'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tx-hep',
    userId: demoUserId,
    accountId: 'account-current',
    categoryId: 'category-housing',
    type: 'expense',
    amount: 74.8,
    currency: 'EUR',
    exchangeRate: 1,
    amountBase: 74.8,
    description: 'HEP račun',
    merchant: 'HEP',
    transactionDate: '2026-09-03',
    labelIds: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tx-ina',
    userId: demoUserId,
    accountId: 'account-wallet',
    categoryId: 'category-transport',
    type: 'expense',
    amount: 48.2,
    currency: 'EUR',
    exchangeRate: 1,
    amountBase: 48.2,
    description: 'Gorivo',
    merchant: 'INA',
    transactionDate: '2026-09-01',
    labelIds: [],
    createdAt: now,
    updatedAt: now,
  },
]

export const demoRecurring: RecurringTransaction[] = [
  {
    id: 'rec-netflix',
    userId: demoUserId,
    accountId: 'account-visa',
    categoryId: 'category-subscriptions',
    type: 'expense',
    amount: 13.99,
    currency: 'EUR',
    frequency: 'monthly',
    interval: 1,
    startDate: '2026-01-09',
    nextRunAt: '2026-09-09',
    active: true,
    autoLog: true,
    description: 'Netflix Standard',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rec-rent',
    userId: demoUserId,
    accountId: 'account-current',
    categoryId: 'category-housing',
    type: 'expense',
    amount: 450,
    currency: 'EUR',
    frequency: 'monthly',
    interval: 1,
    startDate: '2026-01-15',
    nextRunAt: '2026-09-15',
    active: true,
    autoLog: false,
    description: 'Stanarina / Režije',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rec-salary',
    userId: demoUserId,
    accountId: 'account-current',
    categoryId: 'category-salary',
    type: 'income',
    amount: 2800,
    currency: 'EUR',
    frequency: 'monthly',
    interval: 1,
    startDate: '2026-01-06',
    nextRunAt: '2026-10-06',
    active: true,
    autoLog: true,
    description: 'Mjesečna plaća',
    createdAt: now,
    updatedAt: now,
  },
]

export function createDemoSummary(): DashboardSummary {
  const expenses = demoTransactions
    .filter((tx) => tx.type === 'expense')
    .reduce((sum, tx) => sum + tx.amountBase, 0)
  const income = demoTransactions
    .filter((tx) => tx.type === 'income')
    .reduce((sum, tx) => sum + tx.amountBase, 0)
  const categoryTotals = demoCategories
    .filter((category) => category.type === 'expense' && !category.parentId)
    .map((category) => ({
      categoryId: category.id,
      name: category.name,
      amount: demoTransactions
        .filter(
          (tx) =>
            tx.categoryId === category.id ||
            demoCategories.find((child) => child.id === tx.categoryId)?.parentId === category.id,
        )
        .reduce((sum, tx) => sum + (tx.type === 'expense' ? tx.amountBase : 0), 0),
      percentage: 0,
      color: category.color,
    }))
    .filter((item) => item.amount > 0)
  return {
    balance: demoAccounts.reduce((sum, account) => sum + account.balance, 0),
    income,
    expenses,
    netCashFlow: income - expenses,
    previousNetCashFlow: 1100,
    transactionCount: demoTransactions.length,
    cashFlow: [
      { label: 'Pon', income: 520, expenses: 280 },
      { label: 'Uto', income: 400, expenses: 330 },
      { label: 'Sri', income: 710, expenses: 220 },
      { label: 'Čet', income: 900, expenses: 190 },
      { label: 'Pet', income: 570, expenses: 240 },
      { label: 'Sub', income: 310, expenses: 410 },
      { label: 'Ned', income: 380, expenses: 180 },
    ],
    categoryBreakdown: categoryTotals.map((item) => ({
      ...item,
      percentage: Math.round((item.amount / Math.max(expenses, 1)) * 100),
    })),
    topMerchants: [
      { merchant: 'Konzum', amount: 1201.2, count: 14 },
      { merchant: 'HEP', amount: 743.6, count: 3 },
      { merchant: 'INA', amount: 286, count: 5 },
    ],
  }
}
