import {
  Activity,
  Archive,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  ChartNoAxesCombined,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  CreditCard,
  Download,
  Eye,
  FileText,
  Fuel,
  House,
  Landmark,
  LayoutDashboard,
  ListFilter,
  Menu,
  MoreHorizontal,
  Pencil,
  Plus,
  Receipt,
  Search,
  Settings2,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Tags,
  Trash2,
  TrendingUp,
  Upload,
  UserRound,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  'arrow-down-right': ArrowDownRight,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-right': ArrowUpRight,
  analytics: ChartNoAxesCombined,
  'bar-chart': BarChart3,
  bell: Bell,
  'briefcase-business': BriefcaseBusiness,
  'calendar-days': CalendarDays,
  card: CreditCard,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  currency: CircleDollarSign,
  download: Download,
  eye: Eye,
  'file-text': FileText,
  fuel: Fuel,
  house: House,
  landmark: Landmark,
  dashboard: LayoutDashboard,
  filter: ListFilter,
  menu: Menu,
  more: MoreHorizontal,
  pencil: Pencil,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  settings: Settings2,
  'shopping-cart': ShoppingCart,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  tags: Tags,
  trash: Trash2,
  trend: TrendingUp,
  upload: Upload,
  user: UserRound,
  wallet: Wallet,
  x: X,
}

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.8,
}: {
  name: string
  size?: number
  strokeWidth?: number
}) {
  const Component = icons[name] ?? Sparkles
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden="true" />
}
