import {
  Activity,
  Archive,
  Apple,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpRight,
  BarChart3,
  Baby,
  Bell,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CakeSlice,
  CalendarDays,
  Car,
  Cat,
  ChartNoAxesCombined,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  CreditCard,
  Coffee,
  Download,
  Dumbbell,
  Eye,
  FileText,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Heart,
  House,
  Laptop,
  Landmark,
  LayoutDashboard,
  ListFilter,
  LogOut,
  Menu,
  MoreHorizontal,
  Music,
  PawPrint,
  Pencil,
  Pill,
  Pizza,
  Plus,
  Receipt,
  Search,
  Share,
  Settings2,
  ShoppingCart,
  ShoppingBag,
  SlidersHorizontal,
  Smartphone,
  Sofa,
  Salad,
  Sparkles,
  Stethoscope,
  Tags,
  Trash2,
  TrendingUp,
  Train,
  Utensils,
  Upload,
  UserRound,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  apple: Apple,
  'arrow-down-right': ArrowDownRight,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-right': ArrowUpRight,
  analytics: ChartNoAxesCombined,
  'bar-chart': BarChart3,
  baby: Baby,
  bell: Bell,
  bike: Bike,
  'book-open': BookOpen,
  'briefcase-business': BriefcaseBusiness,
  bus: Bus,
  cake: CakeSlice,
  'calendar-days': CalendarDays,
  car: Car,
  cat: Cat,
  card: CreditCard,
  coffee: Coffee,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  currency: CircleDollarSign,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  'file-text': FileText,
  fuel: Fuel,
  gamepad: Gamepad2,
  gem: Gem,
  gift: Gift,
  'graduation-cap': GraduationCap,
  heart: Heart,
  house: House,
  laptop: Laptop,
  landmark: Landmark,
  dashboard: LayoutDashboard,
  filter: ListFilter,
  'log-out': LogOut,
  menu: Menu,
  more: MoreHorizontal,
  music: Music,
  'paw-print': PawPrint,
  pencil: Pencil,
  pill: Pill,
  pizza: Pizza,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  share: Share,
  settings: Settings2,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  salad: Salad,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  sofa: Sofa,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  tags: Tags,
  trash: Trash2,
  trend: TrendingUp,
  train: Train,
  utensils: Utensils,
  upload: Upload,
  user: UserRound,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  x: X,
  zap: Zap,
}

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.8,
}: {
  name: string
  size?: number
  strokeWidth?: number
}) {
  const Component = icons[name] ?? Sparkles
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden="true" />
}
